# -*- coding: utf-8 -*-
"""Práctica-1-Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13yOSsyF-I6tvn5QEU_ZQrq7aG-2TrjUx

# Bienvenido a Python
### Curso-Codifica Software De Sistemas Informáticos
##### Prof.Luis Alfonso Martínez Alfaro

## Introducción

¡Hola! En esta práctica, aprenderás a interactuar con el usuario y a utilizar algunas funciones básicas en Python. Sigue las instrucciones para armar tu programa poco a poco.

---

## Paso 1: Bienvenida al usuario

Vamos a comenzar creando un mensaje de bienvenida. Escribe el siguiente código en tu editor de Python que aparece abajo:

```python
print("Bienvenido a Python por favor sigue las instrucciones")
```
"""

print("Bienvenido a Python por favor sigue las instrucciones")

"""---
##Paso 2: Pedir el nombre del usuario

##Ahora vamos a pedir al usuario que ingrese su nombre. Escribe el siguiente código en tu editor de Python que aparece abajo:

```python
nombre = input("Ingresa tu nombre: ")
```


"""

nombre = input("Ingresa tu nombre: ")

"""---
##Paso 3: Saludar al usuario por su nombre

##Vamos a utilizar el nombre que ingresó el usuario para saludarlo. Añade la siguiente línea de código:

```python
print("Hola", nombre, "espero que disfrutes de Python")
```
"""

print("Hola", nombre, "espero que disfrutes de Python")

"""---
##Paso 4: Contar los caracteres del nombre


##Finalmente, vamos a contar cuántos caracteres tiene el nombre del usuario y mostrar esta información. Añade la siguiente línea de código:


```python
print("El número de caracteres en tu nombre es:", len(nombre))
```
"""



"""---
##Paso 5: Agrega algo extra


##¡Bien hecho! Ahora tu programa debería verse así:


```python
print("Bienvenido a Python por favor sigue las instrucciones")
nombre = input("Ingresa tu nombre: ")
print("Hola", nombre, "espero que disfrutes de Python")
print("El número de caracteres en tu nombre es:", len(nombre))

```
##Desafio

##Vamos a pedir más información al usuario: su edad, fecha de nacimiento y lugar de nacimiento. Luego, muestra esta información en un nuevo codigo en el editor que viene debajo.


"""

